### ISSUE TITLE
Skript version 2.6-Alpha1

### ISSUE THREAD

**Issue by MennoGamed** [APickledWalrus/skript-placeholders#24]
**Description:**
Since the release of Skript version 2.6-alpha1, this plugin breaks. It can no longer load placeholders.

**Steps to Reproduce:**
1. Install skript version 2.6-alpha 1 on a 1.16.5 server. (paper-spigot for me)
2. Install a script that uses placeholders. (placeholderAPI)
3. View the console for the errors. (you only get an error from the code itself, not from the plugin)

**Expected Behavior:**
That the plugin is functioning. not like in skript version 2.5.3

**Errors / Screenshots:**
Here's a screenshot as proof that the placeholders are no longer loading:
![image](https://user-images.githubusercontent.com/64696706/119281012-347f2080-bc34-11eb-8469-5fd13d226fec.png)

Below is an error from the plugin itself. You get this as soon as you stop the server. No errors at start-up.
Error link: https://pastebin.com/AMZEdkvN

### Server Information
* **Server version/platform:** Paper version git-Paper-720 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* **skript-placeholders version:**  1.5.1
* **Skript version:** 2.6-alpha 1
* **PlaceholderAPI version:** 2.10.9

**Comment by APickledWalrus** [comment]
Skript has removed the need to use double quotes (e.g. "") in expressions that are in strings. For example:

Instead of doing `send "%placeholder ""luckperms_prefix"" from player%" to all players` you could do `send "%placeholder "luckperms_prefix" from player%" to all players`

Please let me know if this fixes the issue with placeholders not loading. You also seem to be using skUtilities. I **strongly** recommend you switch to skript-yaml as skUtilities is no longer maintained and does not do YAML as efficiently.

**Comment by MennoGamed** [comment]
Thanks for the quick response.
And I have to say, the problem is completely solved with that.

And thanks for the tip to start using skript-yaml.

**Comment by APickledWalrus** [comment]
Of course! If you have any other issues with this addon, please feel free to ask.
